# Generated by Django 3.0.7 on 2020-12-23 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('ids', models.AutoField(primary_key=True, serialize=False)),
                ('akun_reporting', models.CharField(max_length=30)),
                ('telp_reported', models.CharField(max_length=12)),
                ('akun_reported', models.CharField(max_length=30)),
                ('kodeorder_report', models.CharField(max_length=100)),
                ('noted_report', models.TextField()),
                ('datetime_report', models.DateTimeField(auto_now_add=True)),
                ('upload_foto', models.ImageField(upload_to='avatar/')),
                ('status_report', models.CharField(max_length=20)),
            ],
        ),
    ]
