# Generated by Django 3.0.7 on 2020-12-23 09:33

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='upload_foto',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='avatar/'), upload_to=''),
        ),
    ]
