# Generated by Django 3.0.7 on 2020-12-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20201223_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='upload_foto',
            field=models.ImageField(upload_to='avatar/'),
        ),
    ]
