# Generated by Django 3.0.7 on 2020-09-28 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bukajasa',
            fields=[
                ('nama_jasa', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('pemilik_jasa', models.CharField(max_length=25)),
                ('email_jasa', models.EmailField(max_length=25)),
                ('alamat', models.CharField(max_length=100)),
                ('kota', models.CharField(default='', max_length=25)),
                ('provinsi', models.CharField(default='', max_length=30)),
                ('no_telp', models.CharField(max_length=20)),
                ('deskripsi_toko', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
