# Generated by Django 3.0.7 on 2020-09-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_auto_20200928_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='bukajasa',
            name='jenis_jasa',
            field=models.CharField(choices=[('Pendidikan', 'Pendidikan'), ('Usaha Rumah Tangga', 'Usaha Rumah Tangga'), ('Transportasi', 'Transportasi'), ('Desain', 'Desain'), ('Teknologi', 'Teknologi')], default='', max_length=30),
        ),
    ]
