# Generated by Django 3.0.7 on 2020-09-28 17:57

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0004_auto_20200928_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bukajasa',
            name='jenis_jasa',
        ),
        migrations.CreateModel(
            name='postingjasa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jasa', models.CharField(max_length=50)),
                ('harga_jasa', models.IntegerField(default=0)),
                ('satuan_jasa', models.CharField(choices=[('KG', 'KG'), ('KM', 'KM'), ('JAM', 'JAM'), ('HARI', 'HARI'), ('QTY', 'QTY')], default='', max_length=10)),
                ('jenis_jasa', models.CharField(choices=[('Pendidikan', 'Pendidikan'), ('Usaha Rumah Tangga', 'Usaha Rumah Tangga'), ('Transportasi', 'Transportasi'), ('Desain', 'Desain'), ('Teknologi', 'Teknologi')], default='', max_length=30)),
                ('slug_jasa', models.SlugField()),
                ('status_jasa', models.CharField(choices=[('ADA', 'ADA'), ('SIBUK', 'SIBUK')], default='ADA', max_length=10)),
                ('upload_foto', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='avatar/'), upload_to='')),
                ('nama_jasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.bukajasa')),
            ],
        ),
    ]
