# Generated by Django 3.0.7 on 2020-10-05 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0006_auto_20201001_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='scorejasa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.FloatField()),
                ('jasa', models.CharField(max_length=50)),
                ('nama_pelanggan', models.CharField(max_length=30)),
                ('nama_jasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.bukajasa')),
            ],
        ),
    ]
