# Generated by Django 3.0.7 on 2020-10-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0008_auto_20201012_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='postingjasa',
            name='keterangan',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
