# Generated by Django 3.0.7 on 2020-10-13 07:00

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0009_postingjasa_keterangan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postingjasa',
            name='upload_foto',
            field=models.ImageField(upload_to=django.core.files.storage.FileSystemStorage(location='avatar/')),
        ),
    ]
