# Generated by Django 3.0.7 on 2020-10-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0010_auto_20201013_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postingjasa',
            name='upload_foto',
            field=models.ImageField(default='', upload_to='avatar/'),
        ),
    ]
