# Generated by Django 3.0.7 on 2020-12-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0013_scorejasa_kode_pesan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postingjasa',
            name='slug_jasa',
        ),
        migrations.AlterField(
            model_name='postingjasa',
            name='status_jasa',
            field=models.CharField(choices=[('Ada', 'Ada'), ('Sibuk', 'Sibuk')], max_length=10),
        ),
    ]
