# Generated by Django 3.0.7 on 2020-12-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0014_auto_20201211_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bukajasa',
            name='kecamatan',
            field=models.CharField(choices=[('Bodeh', 'Bodeh'), ('Petarukan', 'Petarukan'), ('Taman', 'Taman'), ('Randudongkal', 'Randudongkal'), ('Ulujami', 'Ulujami'), ('Bantarbolang', 'Bantarbolang'), ('Comal', 'Comal'), ('Ampelgading', 'Ampelgading'), ('Watukumpul', 'Watukumpul'), ('Pemalang', 'Pemalang'), ('Belik', 'Belik'), ('Pulosari', 'Pulosari'), ('Moga', 'Moga'), ('Warungpring', 'Warungpring')], max_length=25),
        ),
        migrations.AlterField(
            model_name='postingjasa',
            name='harga_jasa',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='postingjasa',
            name='jenis_jasa',
            field=models.CharField(choices=[('Pendidikan', 'Pendidikan'), ('Usaha Rumah Tangga', 'Usaha Rumah Tangga'), ('Transportasi', 'Transportasi'), ('Desain', 'Desain'), ('Teknologi', 'Teknologi')], max_length=30),
        ),
        migrations.AlterField(
            model_name='postingjasa',
            name='satuan_jasa',
            field=models.CharField(choices=[('KG', 'KG'), ('KM', 'KM'), ('JAM', 'JAM'), ('HARI', 'HARI'), ('QTY', 'QTY')], max_length=10),
        ),
    ]
