# Generated by Django 3.0.7 on 2020-12-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0015_auto_20201212_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postingjasa',
            name='satuan_jasa',
            field=models.CharField(choices=[('KG', 'KG'), ('KM', 'KM'), ('JAM', 'JAM'), ('HARI', 'HARI'), ('BULAN', 'BULAN'), ('QTY', 'QTY')], max_length=10),
        ),
    ]
