# Generated by Django 3.0.7 on 2021-01-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0016_auto_20201220_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorejasa',
            name='ulasan',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scorejasa',
            name='upload_foto',
            field=models.ImageField(blank=True, upload_to='avatar/'),
        ),
    ]
