# Generated by Django 3.0.7 on 2021-01-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0017_auto_20210102_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postingjasa',
            name='satuan_jasa',
            field=models.CharField(choices=[('KG', 'KG'), ('KM', 'KM'), ('JAM', 'JAM'), ('HARI', 'HARI'), ('BULAN', 'BULAN'), ('QTY', 'QTY'), ('PCS', 'PCS')], max_length=10),
        ),
    ]
