# Generated by Django 3.0.7 on 2020-09-18 17:54

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.FileField(null=True, storage=(django.core.files.storage.FileSystemStorage(location='avatar'),), upload_to=''),
        ),
    ]
