# Generated by Django 3.0.7 on 2020-09-18 18:03

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20200918_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='avatar/'), upload_to=''),
        ),
    ]
