# Generated by Django 3.0.7 on 2020-10-07 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20200918_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('Customer', 'Pelanggan'), ('Provider', 'Penyedia Jasa')], max_length=10),
        ),
    ]
