# Generated by Django 3.0.7 on 2020-10-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20201007_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='no_telp',
            field=models.CharField(default='-', max_length=13),
            preserve_default=False,
        ),
    ]
