# Generated by Django 3.0.7 on 2020-10-09 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_userprofile_no_telp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='no_telp',
        ),
    ]
