# Generated by Django 3.0.7 on 2020-10-02 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='order',
            new_name='pesan',
        ),
    ]
