# Generated by Django 3.0.7 on 2020-10-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20201002_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesan',
            name='kecamatan_order',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
