# Generated by Django 3.0.7 on 2020-10-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_pesan_kecamatan_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesan',
            name='akun_pemesan',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
