# Generated by Django 3.0.7 on 2020-10-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_pesan_akun_pemesan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesan',
            name='catatan_order',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
