# Generated by Django 3.0.7 on 2020-10-07 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_pesan_gambar_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesan',
            name='akun_provider',
            field=models.CharField(default='jisoo', max_length=25),
            preserve_default=False,
        ),
    ]
