# Generated by Django 3.0.7 on 2020-10-08 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0007_scorejasa'),
        ('order', '0007_pesan_akun_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesan',
            name='jasa_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.postingjasa'),
        ),
    ]
