# Generated by Django 3.0.7 on 2020-10-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20201008_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesan',
            name='telp_order',
            field=models.CharField(default='', max_length=13),
            preserve_default=False,
        ),
    ]
