# Generated by Django 3.0.7 on 2020-12-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_pesan_telp_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesan',
            name='kecamatan_order',
            field=models.CharField(choices=[('Bodeh', 'Bodeh'), ('Petarukan', 'Petarukan'), ('Taman', 'Taman'), ('Randudongkal', 'Randudongkal'), ('Ulujami', 'Ulujami'), ('Bantarbolang', 'Bantarbolang'), ('Comal', 'Comal'), ('Ampelgading', 'Ampelgading'), ('Watukumpul', 'Watukumpul'), ('Pemalang', 'Pemalang'), ('Belik', 'Belik'), ('Pulosari', 'Pulosari'), ('Moga', 'Moga'), ('Warungpring', 'Warungpring')], max_length=30),
        ),
    ]
