# Generated by Django 3.0.7 on 2020-12-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20201211_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesan',
            name='providertelp',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pesan',
            name='telp_order',
            field=models.CharField(max_length=12),
        ),
    ]
