# Generated by Django 3.0.7 on 2021-01-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20201222_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesan',
            name='nama_order',
            field=models.CharField(error_messages={'required': 'Silahkan masukan nama lengkap'}, max_length=30),
        ),
    ]
