# Generated by Django 3.0.7 on 2021-01-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20210124_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesan',
            name='nama_order',
            field=models.CharField(max_length=30),
        ),
    ]
